version: '3.8'

services:
  inventory-srv:
    build:
      context: .
      dockerfile: ./services/inventory-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:1993@postgres:5432/inventory_saas
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  auth-srv:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    ports:
      - '3001:3001'

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1993
      - POSTGRES_DB=inventory_saas
    ports:
      - '1993:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
